/**
 * REST Auth
 * API for Authentication Node
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the io.swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.api;

import io.swagger.model.ModelApiResponse;
import io.swagger.model.User;
import org.junit.Test;
import org.junit.Before;
import static org.junit.Assert.*;

import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.client.JAXRSClientFactory;
import org.apache.cxf.jaxrs.client.ClientConfiguration;
import org.apache.cxf.jaxrs.client.WebClient;


import com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;




/**
 * REST Auth
 *
 * <p>API for Authentication Node
 *
 * API tests for UserApi 
 */
public class UserApiTest {


    private UserApi api;
    
    @Before
    public void setup() {
        JacksonJsonProvider provider = new JacksonJsonProvider();
        List providers = new ArrayList();
        providers.add(provider);
        
        api = JAXRSClientFactory.create("http://localhost/authentication", UserApi.class, providers);
        org.apache.cxf.jaxrs.client.Client client = WebClient.client(api);
        
        ClientConfiguration config = WebClient.getConfig(client); 
    }

    
    /**
     * Check if user exists
     *
     * It can be used to check whether a user exists or not
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void checkIfUserIsRegisteredTest() {
        String username = null;
        //ModelApiResponse response = api.checkIfUserIsRegistered(username);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Create new user
     *
     * A new user is inserted into the database, if it doesn&#39;t exist
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void insertUserTest() {
        User user = null;
        //ModelApiResponse response = api.insertUser(user);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
    /**
     * Logs user into the system
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void loginUserTest() {
        User body = null;
        //ModelApiResponse response = api.loginUser(body);
        //assertNotNull(response);
        // TODO: test validations
        
        
    }
    
}
